{% set version = "0.1.0" %}

package:
  name: pyebsdindex-meta
  version: {{ version }}

source:
  fn: pyebsdindex-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyebsdindex/pyebsdindex-{{ version }}.tar.gz
  sha256: 2c8456b45bf2bf8d152650fc063927d9ebb62a0cbb24836c890e9658b16907ee

build:
  number: 1

requirements:
  build:
    - python
  host:
    - python

outputs:
  - name: pyebsdindex-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - python
      host:
        - python
        - pip
      run:
        - h5py
        - jupyterlab
        - matplotlib-base
        - numba
        - numpy
        - ocl-icd-system  # [linux]
        - ocl_icd_wrapper_apple  # [osx]
        - pyopencl
        - pyswarms
        - python
        - scipy
    test:
      requires:
        - pip
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
      commands:
        - pip check
        - pytest --pyargs pyebsdindex -k "not test_index_pats and not test_pc_optimize and not test_pc_optimize_pso"

  - name: pyebsdindex
    build:
      skip: true  # [osx]
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('pyebsdindex-base', exact=True) }}
        - ray-default
    test:
      requires:
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
      commands:
        - pytest --pyargs pyebsdindex -k "not test_index_pats and not test_pc_optimize and not test_pc_optimize_pso"

about:
  home: https://pyebsdindex.readthedocs.io
  license_file: License
  license: LicenseRef-PyEBSDIndex
  summary: Python based tool for Hough/Radon based EBSD indexing
  doc_url: https://pyebsdindex.readthedocs.io
  dev_url: https://github.com/USNavalResearchLaboratory/PyEBSDIndex

extra:
  recipe-maintainers:
    - drowenhorst-nrl
    - hakonanes
