{% set version = "0.3.8" %}

package:
  name: pyebsdindex-meta
  version: {{ version }}

source:
  fn: pyebsdindex-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/pyebsdindex/pyebsdindex-{{ version }}.tar.gz
  sha256: 368cb2749cef2ed1950040378e4c5c213aced4b572e863b2a5c4ad9ca39b3fda

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}

outputs:
  - name: pyebsdindex-base
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vv
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - __{{ target_os }}
        - python >={{ python_min }}
        - h5py
        - matplotlib-base
        - numba >=0.55.1
        - numpy
        - ocl-icd-system  # [linux]
        - ocl_icd_wrapper_apple  # [osx]
        - pyopencl
        
        - scipy
    test:
      requires:
        - pip
        - pytest
        - python {{ python_min }}
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
        - pyebsdindex.tripletvote
      commands:
        - pip check
        - pytest --pyargs pyebsdindex

  - name: pyebsdindex
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - __{{ target_os }}
        - {{ pin_subpackage('pyebsdindex-base', exact=True) }}
        - ray-default >=2.9
    test:
      requires:
        - pytest
        - python {{ python_min }}
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
        - pyebsdindex.tripletvote
      commands:
        - pytest --pyargs pyebsdindex -k "not test_index_pats_multi"

about:
  home: https://pyebsdindex.readthedocs.io
  license_file: License
  license: LicenseRef-PyEBSDIndex
  summary: Python based tool for Radon based EBSD indexing
  doc_url: https://pyebsdindex.readthedocs.io
  dev_url: https://github.com/USNavalResearchLaboratory/PyEBSDIndex

extra:
  recipe-maintainers:
    - drowenhorst-nrl
    - hakonanes
