{% set version = "0.2.0" %}

package:
  name: pyebsdindex-meta
  version: {{ version }}

source:
  fn: pyebsdindex-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyebsdindex/pyebsdindex-{{ version }}.tar.gz
  sha256: 7ff9bb7984d30e0f023209bb9ec1d11cb077060461f99ef720080f1c0f47b5bb

build:
  number: 0
  noarch: python

requirements:
  host:
    - python

outputs:
  - name: pyebsdindex-base
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vv
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __{{ target_os }}
        - h5py
        - matplotlib-base
        - numba
        - numpy
        - ocl-icd-system  # [linux]
        - ocl_icd_wrapper_apple  # [osx]
        - pyopencl
        - pyswarms
        - python
        - scipy
    test:
      requires:
        - pip
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
      commands:
        - pip check
        - pytest --pyargs pyebsdindex -k "not test_index_pats and not test_pc_optimize and not test_pc_optimize_pso"

  - name: pyebsdindex
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - __{{ target_os }}
        - {{ pin_subpackage('pyebsdindex-base', exact=True) }}
        - ray-default  # [not osx]
    test:
      requires:
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
      commands:
        - pytest --pyargs pyebsdindex -k "not test_index_pats and not test_pc_optimize and not test_pc_optimize_pso"

about:
  home: https://pyebsdindex.readthedocs.io
  license_file: License
  license: LicenseRef-PyEBSDIndex
  summary: Python based tool for Hough/Radon based EBSD indexing
  doc_url: https://pyebsdindex.readthedocs.io
  dev_url: https://github.com/USNavalResearchLaboratory/PyEBSDIndex

extra:
  recipe-maintainers:
    - drowenhorst-nrl
    - hakonanes
