{% set version = "0.3.3" %}

package:
  name: pyebsdindex-meta
  version: {{ version }}

source:
  fn: pyebsdindex-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyebsdindex/pyebsdindex-{{ version }}.tar.gz
  sha256: 5d63e1c71f1ebb320bf914fbd097e4a536033eef3542617cf1a844f25a77738b

build:
  number: 0
  noarch: python

requirements:
  host:
    - python

outputs:
  - name: pyebsdindex-base
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vv
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __{{ target_os }}
        - h5py
        - matplotlib-base
        - numba >=0.53
        - numpy
        - ocl-icd-system  # [linux]
        - ocl_icd_wrapper_apple  # [osx]
        - pyopencl
        - python
        - scipy
    test:
      requires:
        - pip
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
        - pyebsdindex.tripletvote
      commands:
        - pip check
        - pytest --pyargs pyebsdindex

  - name: pyebsdindex
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - __{{ target_os }}
        - {{ pin_subpackage('pyebsdindex-base', exact=True) }}
        - ray-default  # [not osx]
    test:
      requires:
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
        - pyebsdindex.tripletvote
      commands:
        - pytest --pyargs pyebsdindex -k "not test_index_pats_multi"

about:
  home: https://pyebsdindex.readthedocs.io
  license_file: License
  license: LicenseRef-PyEBSDIndex
  summary: Python based tool for Radon based EBSD indexing
  doc_url: https://pyebsdindex.readthedocs.io
  dev_url: https://github.com/USNavalResearchLaboratory/PyEBSDIndex

extra:
  recipe-maintainers:
    - drowenhorst-nrl
    - hakonanes
